services:
  - type: web
    name: socialmedia
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn socialmedia.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: socialmedia-db
          property: connectionString

databases:
  - name: socialmedia-db
    databaseName: socialmedia
    user: socialuser
